<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================================   -->
  <!-- |    This document was autogenerated by xacro from /home/xsquare/catkin_ws/src/gbrobot_common/gbrobot_description/urdf/exv.xacro   | -->
  <!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                   | -->
  <!-- ===================================================================================   -->
  <robot name="exv" xmlns:xacro="http://www.ros.org/wiki/xacro"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"   
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"   
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor">
      <!-- update dicts properties -->
    <update_attrs attr="NoneNone"/>
    <!--   END PARAMETERS -->
    <!-- BASE_FOOTPRINT -->
    <link name="base_footprint"  >
      <visual>
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
        </visual>
    </link>
    <link name="base_link">
      </link>
    <joint name="  base_to_footprint_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.03"  />
      <child link="base_link"/>
      <parent link="base_footprint"/>
    </joint>
      <!-- BODY -->
    <link name="body">
      <visual>
        <origin xyz="0.05   0 0.215"/>
        <geometry>
          <box size="0.1 0.8 0.43"/>
        </geometry>
        </visual>
      <collision>
        <origin xyz="0.05 0 0.215"/>
        <geometry>
            <box size="0.1 0.8 0.43"/>
        </geometry>
      </collision>
        <inertial>
        <mass value="1000"/>
        <inertia ixx="1.0" ixy="0.0"   ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
      <joint name="body_to_base_link_joint" type="fixed">
      <origin rpy="0   0 0" xyz="0.724 0 0"/>
      <child link="body"/>
      <parent link="base_link"  />
    </joint>
    <!-- FOOTPRINT HULL -->
    <link name="footprint_hull">
        <visual>
        <origin xyz="0.4 0 0.215"/>
        <geometry>
          <box   size="0.6 0.8 0.43"/>
        </geometry>
        <material name="red">
            <color rgba="1 0 0 0.5"/>
        </material>
      </visual>
      <collision>
          <origin xyz="0.4 0 0.215"/>
        <geometry>
          <box size="0.6   0.8 0.43"/>
        </geometry>
      </collision>
    </link>
    <joint name="footprint_hull_body_joint" type="fixed">
      <origin rpy="0 0 0" xyz="0 0   0"/>
      <child link="footprint_hull"/>
      <parent link="body"/>
    </joint>
      <gazebo reference="footprint_hull">
      <material>Gazebo/RedTransparentOverlay</material>
      </gazebo>
    <link name="rigth_leg">
      <inertial>
        <mass value="  1"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0"   izz="1.0"/>
      </inertial>
    </link>
    <link name="rigth_leg_load_tyre"  >
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="0.085" radius="0.0425"/>
        </geometry>
          <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
        </visual>
      <collision>
        <max_contacts>2</max_contacts>
        <origin   rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.085"   radius="0.0425"/>
        </geometry>
      </collision>
      <inertial>
          <mass value="100"/>
        <inertia ixx="0" ixy="0.0" ixz="0.0" iyy="  0" iyz="0.0" izz="0"/>
      </inertial>
    </link>
    <joint name="rigth_leg_load_tyre_rigth_leg_joint"   type="continuous">
      <origin rpy="1.5708 0 0" xyz="0 0 0"/>
      <child   link="rigth_leg_load_tyre"/>
      <parent link="rigth_leg"/>
      <axis xyz="  0 0 1"/>
    </joint>
    <gazebo reference="rigth_leg_load_tyre">
      <mu1>inf</mu1>
        <mu2>inf</mu2>
      <material>Gazebo/Black</material>
    </gazebo>
    <joint   name="rigth_leg_to_base_link_joint" type="fixed">
      <origin rpy="0 0 0"   xyz="-0.724 0.19 0.0125"/>
      <child link="rigth_leg"/>
      <parent link="body"/>
      <axis xyz="0 0 0"/>
    </joint>
    <link name="left_leg">
        <inertial>
        <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0"   ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
      <link name="left_leg_load_tyre">
      <visual>
        <origin rpy="0 0 0"   xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.085" radius="  0.0425"/>
        </geometry>
        <material name="black">
          <color rgba="  0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <max_contacts>2</max_contacts>
          <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <cylinder   length="0.085" radius="0.0425"/>
        </geometry>
      </collision>
        <inertial>
        <mass value="100"/>
        <inertia ixx="0" ixy="0.0"   ixz="0.0" iyy="0" iyz="0.0" izz="0"/>
      </inertial>
    </link>
    <joint   name="left_leg_load_tyre_left_leg_joint" type="continuous">
      <origin rpy="  1.5708 0 0" xyz="0 0 0"/>
      <child link="left_leg_load_tyre"/>
      <parent   link="left_leg"/>
      <axis xyz="0 0 1"/>
    </joint>
    <gazebo reference="  left_leg_load_tyre">
      <mu1>inf</mu1>
      <mu2>inf</mu2>
      <material>Gazebo/Black</material>
      </gazebo>
    <joint name="left_leg_to_base_link_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.724 -0.19 0.0125"/>
      <child link="left_leg"  />
      <parent link="body"/>
      <axis xyz="0 0 0"/>
    </joint>
    <link   name="load_fork">
      <visual>
        <origin rpy="0 0 0" xyz="0.0275 0   -0.0275"/>
        <geometry>
          <box size="0.055 0.38 0.055"/>
          </geometry>
      </visual>
    </link>
    <!-- names from ISO 2331 -->
    <link   name="left_load_fork_shank">
      <visual>
        <origin rpy="0 0 0" xyz="  0.0275 0 0"/>
        <geometry>
          <box size="0.055 0.182 0.43"/>
          </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="  0.0275 0 0"/>
        <geometry>
          <box size="0.055 0.182 0.43"/>
          </geometry>
      </collision>
      <inertial>
        <mass value="1"/>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="  1.0"/>
      </inertial>
    </link>
    <link name="left_load_fork_blade">
        <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="1.15 0.182 0.055"/>
        </geometry>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="  1.15 0.182 0.055"/>
        </geometry>
      </collision>
      <inertial>
          <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="  1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
    <gazebo reference="left_load_fork_blade">
      <mu1>inf</mu1>
      <mu2>inf</mu2>
    </gazebo>
      <link name="left_load_fork_blade_stoper">
      <collision>
        <origin rpy="  0 0.7854 0" xyz="0.455 0 0.0275"/>
        <geometry>
          <box size="0.033   0.182 0.033"/>
        </geometry>
      </collision>
      <inertial>
        <mass   value="1"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0"   iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
    <gazebo reference="left_load_fork_blade_stoper">
      <mu1>inf</mu1>
      <mu2>inf</mu2>
    </gazebo>
      <joint name="left_load_fork_shank_to_blade_stoper_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.575 0 -0.2425"/>
      <child link="left_load_fork_blade_stoper"  />
      <parent link="left_load_fork_shank"/>
      <axis xyz="0 0 0"/>
    </joint>
      <joint name="left_load_fork_shank_to_blade_joint" type="fixed">
      <origin   rpy="0 0 0" xyz="-0.575 0 -0.2425"/>
      <child link="left_load_fork_blade"  />
      <parent link="left_load_fork_shank"/>
      <axis xyz="0 0 0"/>
    </joint>
      <joint name="left_load_fork_arm_to_load_fork_joint" type="fixed">
      <origin   rpy="0 0 0" xyz="0 -0.19 -0.215"/>
      <child link="left_load_fork_shank"  />
      <parent link="load_fork"/>
      <axis xyz="0 0 0"/>
    </joint>
    <!--   names from ISO 2331 -->
    <link name="right_load_fork_shank">
      <visual>
          <origin rpy="0 0 0" xyz="0.0275 0 0"/>
        <geometry>
          <box   size="0.055 0.182 0.43"/>
        </geometry>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0.0275 0 0"/>
        <geometry>
          <box   size="0.055 0.182 0.43"/>
        </geometry>
      </collision>
      <inertial>
          <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="  1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
    <link name="right_load_fork_blade"  >
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="1.15 0.182 0.055"/>
        </geometry>
      </visual>
        <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <box size="1.15 0.182 0.055"/>
        </geometry>
      </collision>
        <inertial>
        <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0"   ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
      <gazebo reference="right_load_fork_blade">
      <mu1>inf</mu1>
      <mu2>inf</mu2>
      </gazebo>
    <link name="right_load_fork_blade_stoper">
      <collision>
          <origin rpy="0 0.7854 0" xyz="0.455 0 0.0275"/>
        <geometry>
            <box size="0.033 0.182 0.033"/>
        </geometry>
      </collision>
        <inertial>
        <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0"   ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
      <gazebo reference="right_load_fork_blade_stoper">
      <mu1>inf</mu1>
        <mu2>inf</mu2>
    </gazebo>
    <joint name="right_load_fork_shank_to_blade_stoper_joint"   type="fixed">
      <origin rpy="0 0 0" xyz="-0.575 0 -0.2425"/>
      <child   link="right_load_fork_blade_stoper"/>
      <parent link="right_load_fork_shank"  />
      <axis xyz="0 0 0"/>
    </joint>
    <joint name="right_load_fork_shank_to_blade_joint"   type="fixed">
      <origin rpy="0 0 0" xyz="-0.575 0 -0.2425"/>
      <child   link="right_load_fork_blade"/>
      <parent link="right_load_fork_shank"/>
        <axis xyz="0 0 0"/>
    </joint>
    <joint name="right_load_fork_arm_to_load_fork_joint"   type="fixed">
      <origin rpy="0 0 0" xyz="0 0.19 -0.215"/>
      <child   link="right_load_fork_shank"/>
      <parent link="load_fork"/>
      <axis   xyz="0 0 0"/>
    </joint>
    <joint name="load_fork_to_body_joint" type="prismatic">
      <origin rpy="0 0 0" xyz="0 0 0.485"/>
      <child link="load_fork"/>
      <parent link="body"/>
      <axis xyz="0 0 1"/>
      <limit   effort="30" lower="0" upper="4.0" velocity="0.3"/>
      <dynamics friction="  1e+6"/>
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    <transmission name="load_fork_to_body_joint_transmission" type="  SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
        <joint name="load_fork_to_body_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      <actuator name="motor2">
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <link name="steering_rod">
      <visual>
          <geometry>
          <cylinder length="0.23" radius="0.018"/>
        </geometry>
          <origin rpy="0 0 0" xyz="0 0 0.115"/>
        <material name="red">
            <color rgba="1 0 0 1"/>
        </material>
      </visual>
      <inertial>
          <mass value="1"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="  1.0" iyz="0.0" izz="1.0"/>
      </inertial>
    </link>
    <gazebo reference="  steering_rod">
      <mu1>0</mu1>
      <mu2>0</mu2>
      <material>Gazebo/Red</material>
      </gazebo>
    <link name="drive_wheel">
      <visual>
        <geometry>
            <cylinder length="0.09" radius="0.115"/>
        </geometry>
        <origin   rpy="0 0 0" xyz="0 0 0"/>
        <material name="black">
          <color   rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <max_contacts>2</max_contacts>
          <geometry>
          <cylinder length="0.09" radius="0.115"/>
        </geometry>
        </collision>
      <inertial>
        <mass value="100"/>
        <inertia ixx="  0" ixy="0.0" ixz="0.0" iyy="0" iyz="0.0" izz="0"/>
      </inertial>
      </link>
    <gazebo reference="drive_wheel">
      <mu1>inf</mu1>
      <mu2>inf</mu2>
        <material>Gazebo/Black</material>
    </gazebo>
    <joint name="drive_wheel_joint"   type="continuous">
      <parent link="steering_rod"/>
      <child link="drive_wheel"/>
      <origin rpy="1.5707 0 1.5707" xyz="0 0 0"/>
      <axis   xyz="0 0 1"/>
      <dynamics damping="1.5" friction="100.0"/>
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    <transmission name="drive_wheel_joint_transmission" type="SimpleTransmission"  >
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="drive_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
      <actuator name="motor1">
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <joint name="drive_steer_joint" type="revolute">
      <parent link="body"/>
      <child link="steering_rod"/>
        <origin rpy="0 0 1.5707" xyz="0.662 -0.267 0.085"/>
      <axis xyz="0 0   1"/>
      <dynamics damping="1.7" friction="100.0"/>
      <limit effort="  30" lower="-3.1416" upper="3.1416" velocity="2.0"/>
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    <transmission name="drive_steer_joint_transmission" type="SimpleTransmission"  >
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="  drive_steer_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      <actuator name="motor3">
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <!-- CASTOR -->
    <link name="castor_ball"  >
      <visual>
        <geometry>
          <sphere radius="0.05"/>
        </geometry>
          <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="black">
            <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
          <max_contacts>2</max_contacts>
        <geometry>
          <box size="0.1   0.1 0.1"/>
          <!-- <sphere radius="${castor_diamiter/2.0}"/> -->
          </geometry>
      </collision>
      <inertial>
        <mass value="100"/>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="  1.0"/>
      </inertial>
    </link>
    <gazebo reference="castor_ball">
      <mu1>0</mu1>
        <mu2>0</mu2>
      <material>Gazebo/Black</material>
    </gazebo>
    <joint   name="base_to_castor_ball" type="continuous">
      <parent link="body"/>
        <child link="castor_ball"/>
      <origin rpy="1.5707 0 0" xyz="0.662 0.267   0.02"/>
      <axis xyz="1 1 1"/>
    </joint>
    <link name="hokuyo_link"  >
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <!-- <mesh filename="package://gbrobot_description/urdf/EVX_14/meshes/hokuyo.dae"/> -->
            <box size="0.1   0.1 0.1"/>
          </geometry>
      </visual>
    </link>
    <gazebo reference="hokuyo_link"  >
      <sensor name="/scan_sensor" type="ray">
        <pose>0 0 0 0 0 0</pose>
          <visualize>false</visualize>
        <update_rate>20</update_rate>
          <ray>
          <scan>
            <horizontal>
              <samples>10080</samples>
                <resolution>1</resolution>
              <min_angle>-6.28319</min_angle>
                <max_angle>-0.0</max_angle>
            </horizontal>
          </scan>
            <range>
            <min>0.10</min>
            <max>30.0</max>
              <resolution>0.01</resolution>
          </range>
          <noise>
              <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
            </noise>
        </ray>
        <plugin filename="libgazebo_ros_laser.so"   name="gazebo_ros_head_hokuyo_controller">
        <box size="0.1   0.1 0.1"/>
          <topicName>/scan</topicName>
            <frameName>hokuyo_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
      <joint name="hokuyo_joint" type="fixed">
      <parent link="base_footprint"  />
      <child link="hokuyo_link"/>
      <origin rpy="0.0 0.0 1.562451" xyz="  1.05 0.002404 2.1"/>
      <axis xyz="0 1 0"/>
    </joint>
    <!-- IMU -->
      <!-- TODO: Disable for simulation -->
    <link name="gx5_link">
      <visual>
          <geometry>
          <sphere radius="0.01"/>
        </geometry>
      </visual>
      </link>
    <joint name="imu_joint" type="fixed">
      <parent link="base_footprint"  />
      <child link="gx5_link"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
        <axis xyz="0 0 0"/>
    </joint>
    <link name="front_nav_lidar_link">
        <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <!-- <mesh filename="package://gbrobot_description/urdf/EVX_14/meshes/hokuyo.dae"/> -->
            <box size="0.1   0.1 0.1"/>
          </geometry>
      </visual>
    </link>
    <gazebo reference="front_nav_lidar_link"  >
      <sensor name="/scan_front_sensor" type="ray">
        <pose>0 0 0 0 0   0</pose>
        <visualize>true</visualize>
        <update_rate>20</update_rate>
          <ray>
          <scan>
            <horizontal>
              <samples>1024</samples>
                <resolution>1</resolution>
              <min_angle>-1.35619</min_angle>
                <max_angle>1.35619</max_angle>
            </horizontal>
          </scan>
            <range>
            <min>0.10</min>
            <max>30.0</max>
              <resolution>0.01</resolution>
          </range>
          <noise>
              <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
            </noise>
        </ray>
        <plugin filename="libgazebo_ros_laser.so"   name="gazebo_ros_head_hokuyo_controller">
          <topicName>/scan_front</topicName>
            <frameName>front_nav_lidar_link</frameName>
        </plugin>
      </sensor>
      </gazebo>
    <joint name="front_nav_lidar_link_joint" type="fixed">
        <parent link="base_footprint"/>
      <child link="front_nav_lidar_link"/>
        <origin rpy="0.0 3.14159 -2.5099763371314934" xyz="1.61762496828 0.373434778941   0.068"/>
      <axis xyz="0 1 0"/>
    </joint>
    <link name="back_nav_lidar_link"  >
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <!-- <mesh filename="package://gbrobot_description/urdf/EVX_14/meshes/hokuyo.dae"/> -->
            <box size="0.1   0.1 0.1"/>
          </geometry>
      </visual>
    </link>
    <gazebo reference="back_nav_lidar_link"  >
      <sensor name="/scan_back_sensor" type="ray">
        <pose>0 0 0 0 0 0</pose>
          <visualize>true</visualize>
        <update_rate>20</update_rate>
          <ray>
          <scan>
            <horizontal>
              <samples>1024</samples>
                <resolution>1</resolution>
              <min_angle>-2.253</min_angle>
                <max_angle>2.35619</max_angle>
            </horizontal>
          </scan>
            <range>
            <min>0.10</min>
            <max>30.0</max>
              <resolution>0.01</resolution>
          </range>
          <noise>
              <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.001</stddev>
            </noise>
        </ray>
        <plugin filename="libgazebo_ros_laser.so"   name="gazebo_ros_head_hokuyo_controller">
          <topicName>/scan_back</topicName>
            <frameName>back_nav_lidar_link</frameName>
        </plugin>
      </sensor>
      </gazebo>
    <joint name="back_nav_lidar_link_joint" type="fixed">
      <parent   link="base_footprint"/>
      <child link="back_nav_lidar_link"/>
      <origin   rpy="0.0 3.14159 1.342974 " xyz="0.841844 -0.434569 0.068"/>
      <axis xyz="  0 1 0"/>
    </joint>
    <!-- VIRTUAL RANGE FINDERS -->
    <link name="virtual_range_finders_1d_right_link"  >
      <!-- <visual>
              <geometry>
                  <box size="0.05 0.05   0.05"/>
              </geometry>
          </visual> -->
    </link>
    <joint   name="virtual_range_finders_1d_right_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="virtual_range_finders_1d_right_link"/>
        <origin rpy="0 0 3.1415925" xyz="0.629 0.55 0.068"/>
      <axis xyz="  0 0 0"/>
    </joint>
    <link name="virtual_range_finders_1d_left_link">
        <!-- <visual>
              <geometry>
                  <box size="0.05 0.05   0.05"/>
              </geometry>
          </visual> -->
    </link>
    <joint   name="virtual_range_finders_1d_left_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="virtual_range_finders_1d_left_link"/>
        <origin rpy="0 0 3.1415925" xyz="0.629 -0.55 0.068"/>
      <axis xyz="  0 0 0"/>
    </joint>
    <joint name="O3D301_link_depth_joint" type="fixed"  >
      <!-- these values have to be these values otherwise the gazebo camera
            image won't be aligned properly with the frame it is supposedly
            originating from -->
      <origin rpy="-1.5708 0 -1.5708" xyz="0 0 0"/>
        <parent link="O3D301_link"/>
      <child link="O3D301_link_depth"/>
      </joint>
    <link name="O3D301_link">
      <visual>
        <origin rpy="0 0   0" xyz="0 0 0"/>
        <geometry>
          <box size="0.095 0.067 0.072"  />
        </geometry>
        <material name="black">
          <color rgba="0   0 0 1"/>
        </material>
      </visual>
    </link>
    <link name="O3D301_link_depth"  >
    </link>
    <gazebo reference="O3D301_link">
      <sensor name="O3D301_link"   type="depth">
        <update_rate>25</update_rate>
        <camera>
            <!-- <vertical_fov>0.7</vertical_fov> unsupported -->
          <horizontal_fov>1.047</horizontal_fov>
            <image>
            <format>R8G8B8</format>
            <width>352</width>
              <height>264</height>
          </image>
          <clip>
            <near>0.3</near>
              <far>10</far>
          </clip>
          <noise>
            <type>gaussian</type>
              <mean>0.0</mean>
            <stddev>0.02</stddev>
          </noise>
          </camera>
        <plugin filename="libgazebo_ros_openni_kinect.so" name="camera_plugin">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
            <!-- Keep this zero, update_rate in the parent <sensor> tag
                will control the frame rate. -->
          <updateRate>0.0</updateRate>
            <cameraName>O3D301_link</cameraName>
          <imageTopicName>/O3D301_link/depth/image_raw</imageTopicName>
            <cameraInfoTopicName>/O3D301_link/depth/camera_info</cameraInfoTopicName>
            <depthImageTopicName>/O3D301_link/depth/image_raw</depthImageTopicName>
            <depthImageInfoTopicName>/O3D301_link/depth/camera_info</depthImageInfoTopicName>
            <pointCloudTopicName>/O3D301_link/depth/points</pointCloudTopicName>
            <frameName>O3D301_link_depth</frameName>
          <pointCloudCutoff>0.05</pointCloudCutoff>
            <distortionK1>1</distortionK1>
          <distortionK2>1</distortionK2>
            <distortionK3>1</distortionK3>
          <distortionT1>1</distortionT1>
            <distortionT2>1</distortionT2>
          <CxPrime>0</CxPrime>
          <Cx>0</Cx>
            <Cy>0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
          </plugin>
      </sensor>
    </gazebo>
    <joint name="O3D301_joint" type="fixed">
      <parent link="load_fork"/>
      <child link="O3D301_link"/>
        <origin rpy="0.013 0.1905 3.112" xyz="0.0600524 -0.098717 0.13503"/>
        <axis rpy="0 0 0" xyz="0 0 0"/>
    </joint>
    <!-- GAZEBO ROS CONTROLLER   -->
    <gazebo>
      <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control"  >
        <robotNamespace>/</robotNamespace>
        <robotSimType>robot_hardware_sim/RobotHardwareSim</robotSimType>
        </plugin>
    </gazebo>
  </robot>