global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  rolling_window: false
  track_unknown_space: false
  width: 500
  height: 500

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_laser, type: "costmap_2d::VoxelLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}