
  # Publish all joint states -----------------------------------
  joint_state_publisher:
    type: "joint_state_controller/JointStateController"
    publish_rate: 30
  

  tilt_joint_controller:
    type: effort_controllers/JointPositionController
    joint: tilt_joint
    pid: {p: 200.0, i: 0.5, d: 1.0}

  lift_joint_controller:
    type: effort_controllers/JointPositionController
    joint: lift_joint
    pid: {p: 200.0, i: 0.5, d: 1.0}

  sideshift_joint_controller:
    type: effort_controllers/JointPositionController
    joint: sideshift_joint
    pid: {p: 200.0, i: 0.5, d: 1.0}

  pris_joint_controller:
    type: effort_controllers/JointPositionController
    joint: pris_joint
    pid: {p: 200.0, i: 0.5, d: 1.0}


  rear_left_steer_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_steer_joint
    pid: 
       p: 4.0 
       i: 0.01
       d: 1.0
       

  rear_right_steer_joint_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_steer_joint
    pid:  
      p: 4.0 
      i: 0.01
      d: 1.0
      
  wheel_front_left_driving_joint_controller:
   type: effort_controllers/JointVelocityController
   joint: wheel_front_left_driving_joint
   pid:
      p: 20.0 
      i: 0.0
      d: 0.0 
      iclamp: 1000.0
  wheel_front_right_driving_joint_controller:
   type: effort_controllers/JointVelocityController
   joint: wheel_front_right_driving_joint
   pid:
      p: 20.0 
      i: 0.0
      d: 0.0 
      iclamp: 1000.0
     



