<?xml version="1.0" ?>
<robot name="RX20_16" xmlns:xacro="http://www.ros.org/wiki/xacro"> 

  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Robot base dimensions -->
  <xacro:property name="base_length" value="-1.839" /> <!--fake 0.5 real 0.139-->
  <xacro:property name="base_width" value="1.1" /> <!--fake 0.3 real 0.139-->
  <xacro:property name="base_height" value="0.835" /> <!--fake 0.1 real 0.139-->
  <xacro:property name="base_mass" value="10" /> 

  <!-- Wheel link dimensions -->
  <xacro:property name="wheel_radius" value="0.10" /> <!--fake 0.1 real 0.139-->
  <xacro:property name="wheel_thickness" value=".13" /> <!--fake 0.08 real 0.139-->
  <xacro:property name="wheel_mass" value="1" />

  <!-- Steering link dimensions -->
  <xacro:property name="steer_radius" value="0.05" /> 
  <xacro:property name="steer_height" value="0.12" /> 
  <xacro:property name="steer_thickness" value="0.02" />
  <xacro:property name="steer_mass" value="1" />

  <!-- Axle positions -->
  <xacro:property name="axle_offset" value="0.036175" /> <!--fake 0.05 real 0.035-->
  <xacro:property name="steer_offset" value="0.0254" /> <!--fake 0.02 real 0.139-->

  <!--<gazebo>
   
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>"/RX20_16"</robotNamespace>
      <robotSimType>steer_bot_hardware_gazebo/SteerBotHardwareGazebo</robotSimType>
      <legacyModeNS>false</legacyModeNS>
    </plugin>
  </gazebo>-->
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/inertia.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/base.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/nav_lidar.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/detection_lidar.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/d435_camera.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/inertials.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/loading_forklift_joints.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/rear_steer.xacro" />
    <xacro:include filename="$(find forklift_simulator)/urdf/RX20_16/steer_wheels.xacro" />

    <xacro:camera_d435 name="camera" topics_ns="camera" parent="lift_link" publish_pointcloud="true"> <origin xyz="0.02 0 0.1" rpy="0 0 0" /> </xacro:camera_d435>  

 

    <!--<xacro:detection_lidar name="front"  x="0.0"  y="0.0" z="2.0" roll="0" pitch="0" yaw="0" resolution="1"/>-->

    <xacro:nav_lidar name="back"  x="0.4"  y="0.0" z="-0.08" roll="0.0" pitch="0.0" yaw="0" resolution="1"/>

    <!--<xacro:nav_lidar name="front"  x="0"  y="0.4" z="0.1" roll="0" pitch="0" yaw="-1.57" resolution="1"/-->
    
    <!-- <xacro:detection_lidar name="front"  x="0.0"  y="0.0" z="0.6" roll="0" pitch="0" yaw="0" resolution="1"/> -->
 <xacro:rear_steer
    name="rear"
    parent="base"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${steer_height-.06}">
</xacro:rear_steer>
 <xacro:rear_wheel
    name="front"
    parent="base"
    wheel_radius="${wheel_radius/4}"
    wheel_thickness="${base_width}"
    wheel_mass="${wheel_mass}">
    <origin xyz="0 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel>

   <xacro:steer_wheel name="rear_left"  x_steering="-1.429" y_steering="0.404" z_steering="0.06" radius="0.150" width="0.15" flip="-1" />
   <xacro:steer_wheel name="rear_right" x_steering="-1.429" y_steering="-0.404" z_steering="0.06" radius="0.150" width="0.15" flip="-1" />
   <!-- <xacro:rear_wheel_lr 
    name="rear_right"
    parent="base"
    reflect="-1"
    x_steering="-1.429" 
    y_steering="-0.404" 
    z_steering="0.06"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}" 
    wheel_mass="${wheel_mass}" 
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${steer_height}"
    flip = "-1">
  </xacro:rear_wheel_lr>

  <xacro:rear_wheel_lr
    name="rear_left"
    parent="base"
    reflect="1"
    x_steering="-1.429" 
    y_steering="0.404" 
    z_steering="0.06"
    wheel_radius="${wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}" 
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}" 
    steer_mass="${steer_mass}" 
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${steer_height}"
    flip = "-1">
  </xacro:rear_wheel_lr>-->

    <xacro:front_wheel_lr name="front_right" parent = "base" x_loading="0.0" y_loading="-0.466" z_loading="0.0" radius="0.18" width="0.18" flip="-1" />
    <xacro:front_wheel_lr name="front_left" parent = "base" x_loading="0.0" y_loading="0.466" z_loading="0.0" radius="0.18" width="0.18" flip="-1" />

    
</robot>
